import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function GET() {
  const [totalPosts, publishedPosts, draftPosts, autoPosts, totalViews, totalCategories, totalSubscribers, totalComments, totalVisits] =
    await Promise.all([
      prisma.post.count(),
      prisma.post.count({ where: { published: true } }),
      prisma.post.count({ where: { published: false } }),
      prisma.post.count({ where: { autoGenerated: true } }),
      prisma.post.aggregate({ _sum: { views: true } }),
      prisma.category.count(),
      prisma.subscriber.count(),
      prisma.comment.count(),
      prisma.visit.count(),
    ]);

  const recentPosts = await prisma.post.findMany({
    orderBy: { createdAt: "desc" },
    take: 5,
    select: { id: true, title: true, slug: true, published: true, autoGenerated: true, views: true, createdAt: true },
  });

  return NextResponse.json({
    totalPosts,
    publishedPosts,
    draftPosts,
    autoPosts,
    totalViews: totalViews._sum.views || 0,
    totalCategories,
    totalSubscribers,
    totalComments,
    totalVisits,
    recentPosts,
  });
}
