import Link from "next/link";
import Image from "next/image";
import { Clock } from "lucide-react";
import { formatDate } from "@/lib/utils";

interface PostCardProps {
  post: {
    id: string;
    title: string;
    slug: string;
    excerpt: string | null;
    featuredImage: string | null;
    readTime: number;
    publishedAt: Date | string | null;
    createdAt: Date | string;
    autoGenerated: boolean;
    category?: { name: string; slug: string; color: string } | null;
  };
  featured?: boolean;
}

export default function PostCard({ post, featured = false }: PostCardProps) {
  const date = post.publishedAt || post.createdAt;

  if (featured) {
    return (
      <Link href={`/blog/${post.slug}`} className="group block">
        <article className="overflow-hidden bg-white rounded-[0.25rem] card-hover">
          <div className="grid md:grid-cols-5 gap-0">
            {/* Image */}
            <div className="relative aspect-[16/10] md:aspect-auto md:col-span-3 overflow-hidden rounded-l-[0.25rem]">
              <Image
                src={post.featuredImage || "/placeholder.jpg"}
                alt={post.title}
                fill
                className="object-cover transition-transform duration-500 group-hover:scale-105"
                sizes="(max-width: 768px) 100vw, 60vw"
              />
            </div>

            {/* Content */}
            <div className="md:col-span-2 p-6 lg:p-8 flex flex-col justify-center">
              <div className="flex items-center gap-2 mb-3">
                {post.category && (
                  <span className="text-[10px] font-bold uppercase tracking-widest text-[#1a2b3c]">
                    {post.category.name}
                  </span>
                )}
                <span className="text-[10px] text-gray-400">&bull;</span>
                <span className="text-[10px] text-gray-400 flex items-center gap-1">
                  <Clock className="w-3 h-3" />
                  {post.readTime} min
                </span>
              </div>
              <h2 className="serif-headline text-lg lg:text-xl leading-snug mb-3 group-hover:text-[#1a2b3c] transition-colors">
                {post.title}
              </h2>
              {post.excerpt && (
                <p className="text-gray-500 text-sm leading-relaxed line-clamp-3 mb-4">
                  {post.excerpt}
                </p>
              )}
              <time dateTime={new Date(date).toISOString()} className="text-xs text-gray-400 font-medium">
                {formatDate(date)}
              </time>
            </div>
          </div>
        </article>
      </Link>
    );
  }

  return (
    <Link href={`/blog/${post.slug}`} className="group block">
      <article className="overflow-hidden bg-white rounded-[0.25rem] card-hover h-full flex flex-col">
        {/* Image */}
        <div className="relative aspect-video overflow-hidden">
          <Image
            src={post.featuredImage || "/placeholder.jpg"}
            alt={post.title}
            fill
            className="object-cover transition-transform duration-500 group-hover:scale-105"
            sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
          />
        </div>

        {/* Content */}
        <div className="p-4 flex flex-col flex-1">
          {/* Category + Time */}
          <div className="flex items-center gap-2 mb-2.5">
            {post.category && (
              <span className="text-[10px] font-bold uppercase tracking-widest text-[#1a2b3c]">
                {post.category.name}
              </span>
            )}
            <span className="text-[10px] text-gray-400">&bull;</span>
            <span className="text-[10px] text-gray-400 flex items-center gap-1">
              <Clock className="w-3 h-3" />
              {post.readTime} min
            </span>
          </div>

          {/* Headline */}
          <h3 className="serif-headline text-[15px] leading-snug mb-2 group-hover:text-[#1a2b3c] transition-colors line-clamp-2">
            {post.title}
          </h3>

          {/* Excerpt */}
          {post.excerpt && (
            <p className="text-gray-500 text-[13px] leading-relaxed line-clamp-2 mb-3 flex-1">
              {post.excerpt}
            </p>
          )}

          {/* Date */}
          <time dateTime={new Date(date).toISOString()} className="text-xs text-gray-400 font-medium mt-auto pt-3 border-t border-gray-100 block">
            {formatDate(date)}
          </time>
        </div>
      </article>
    </Link>
  );
}
