import { NextRequest, NextResponse } from "next/server";
import { generateAutoPost, fetchFromAllApis, cleanContent, getFullContent } from "@/lib/news";
import { prisma } from "@/lib/prisma";
import { generateSlug, calculateReadTime, generateExcerpt } from "@/lib/utils";
import { broadcastLatestPost } from "@/lib/newsletter";
import { submitUrlToIndex } from "@/lib/indexing";

// Dynamic topics will be loaded from settings

// Helper to format topic strings into human-readable category names
function getCategoryName(topic: string): string {
  const map: Record<string, string> = {
    "war": "War & Conflict",
    "international-politics": "International Politics",
    "diplomacy": "Diplomacy",
    "military": "Military & Defense",
    "geopolitics": "Geopolitics",
  };
  if (map[topic]) return map[topic];
  return topic.split(/[- ]+/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

async function handleAutoGenerate(req: NextRequest) {
  const authHeader = req.headers.get("authorization");
  const cronSecret = process.env.CRON_SECRET;

  if (cronSecret && cronSecret !== "auto-blog-cron-secret-change-this" && authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const settings = await prisma.settings.findUnique({ where: { id: "default" } });
    if (!settings?.autoPostEnabled) {
      return NextResponse.json({ message: "Auto-posting is disabled" });
    }

    const topics = settings?.autoPostCategories
      ? settings.autoPostCategories.split(",").map(t => t.trim().toLowerCase()).filter(Boolean)
      : ["technology", "business", "science", "health", "sports"];

    // Check if ?bulk=true to use all APIs at once
    const url = new URL(req.url);
    const bulk = url.searchParams.get("bulk") === "true";

    if (bulk) {
      // Bulk mode: fetch from ALL configured APIs across ALL topics
      const results: { postId: string; topic: string; apiUsed: string }[] = [];

      for (const topic of topics) {
        const apiBatches = await fetchFromAllApis(topic, 3);

        for (const { articles, apiUsed } of apiBatches) {
          for (const article of articles) {
            // Skip duplicates
            const existing = await prisma.post.findFirst({ where: { title: article.title } });
            if (existing) continue;

            let baseSlug = generateSlug(article.title);
            let slug = baseSlug;
            let counter = 1;
            while (await prisma.post.findUnique({ where: { slug } })) {
              slug = `${baseSlug}-${counter}`;
              counter++;
            }

            const categoryName = getCategoryName(topic);
            const categorySlug = generateSlug(topic);
            
            let dbCategory = await prisma.category.findFirst({ where: { slug: categorySlug } });
            if (!dbCategory) {
              dbCategory = await prisma.category.create({ data: { name: categoryName, slug: categorySlug } });
            }

            const htmlContent = await getFullContent(article);
            const plainContent = cleanContent(article.content || article.description || "");
            const excerpt = generateExcerpt(cleanContent(article.description || plainContent));

            const post = await prisma.post.create({
              data: {
                title: cleanContent(article.title),
                slug,
                content: htmlContent,
                excerpt,
                featuredImage: article.urlToImage || `https://picsum.photos/seed/${slug}/1200/630`,
                published: true,
                autoGenerated: true,
                metaTitle: cleanContent(article.title),
                metaDesc: excerpt,
                metaKeywords: `${categoryName}, news, updates`,
                readTime: calculateReadTime(plainContent),
                sourceUrl: article.url,
                sourceName: `${article.source?.name || "Unknown"} (via ${apiUsed})`,
                categoryId: dbCategory.id,
                publishedAt: new Date(),
              },
            });

            // Send newsletter broadcast if enabled
            if (settings.autoSendNewsletter) {
               await broadcastLatestPost().catch(e => console.error("Broadcast err", e));
            }

            // Auto-Index new post on Google Search Console
            submitUrlToIndex(`${settings.siteUrl}/blog/${slug}`).catch(e => console.error("Google Index err", e));

            results.push({ postId: post.id, topic, apiUsed });
          }
        }
      }

      return NextResponse.json({
        success: true,
        mode: "bulk",
        postsCreated: results.length,
        results,
      });
    }

    // Single mode: pick requested topic or random topic from settings
    let requestedTopic = null;
    try {
      // Only parse json if a body exists
      const bodyText = await req.text();
      if (bodyText) {
        const body = JSON.parse(bodyText);
        if (body?.category) requestedTopic = body.category;
      }
    } catch (e) {
      // Ignored
    }

    const topic = requestedTopic || topics[Math.floor(Math.random() * topics.length)];
    const postId = await generateAutoPost(topic);

    if (postId) {
      return NextResponse.json({ success: true, postId, topic });
    }

    return NextResponse.json({ message: "No new articles to generate" });
  } catch (error) {
    console.error("Auto-generate error:", error);
    return NextResponse.json({ error: "Failed to generate post" }, { status: 500 });
  }
}

export { handleAutoGenerate as GET, handleAutoGenerate as POST };
