"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import {
  FileText,
  Eye,
  Bot,
  FolderOpen,
  TrendingUp,
  PlusCircle,
  ArrowUpRight,
  Users,
  MessageSquare,
  BarChart,
} from "lucide-react";
import { formatDate } from "@/lib/utils";

interface DashboardData {
  totalPosts: number;
  publishedPosts: number;
  draftPosts: number;
  autoPosts: number;
  totalViews: number;
  totalCategories: number;
  totalSubscribers: number;
  totalComments: number;
  totalVisits: number;
  recentPosts: {
    id: string;
    title: string;
    slug: string;
    published: boolean;
    autoGenerated: boolean;
    views: number;
    createdAt: string;
  }[];
}

export default function AdminDashboard() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/dashboard")
      .then((r) => r.json())
      .then(setData)
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="animate-pulse space-y-6">
        <div className="h-8 bg-slate-200 rounded w-48" />
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <div key={i} className="h-28 bg-slate-200 rounded-xl" />
          ))}
        </div>
      </div>
    );
  }

  if (!data) return null;

  const stats = [
    {
      label: "Total Posts",
      value: data.totalPosts,
      icon: FileText,
      color: "bg-blue-50 text-blue-600",
    },
    {
      label: "Total Visits",
      value: data.totalVisits.toLocaleString(),
      icon: BarChart,
      color: "bg-green-50 text-green-600",
    },
    {
      label: "Subscribers",
      value: data.totalSubscribers.toLocaleString(),
      icon: Users,
      color: "bg-purple-50 text-purple-600",
    },
    {
      label: "Comments",
      value: data.totalComments.toLocaleString(),
      icon: MessageSquare,
      color: "bg-amber-50 text-amber-600",
    },
    {
      label: "Total Categories",
      value: data.totalCategories,
      icon: FolderOpen,
      color: "bg-indigo-50 text-indigo-600",
    },
    {
      label: "Auto Generated",
      value: data.autoPosts,
      icon: Bot,
      color: "bg-rose-50 text-rose-600",
    },
  ];

  return (
    <div className="animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Dashboard</h1>
          <p className="text-slate-500 text-sm mt-1">
            Welcome back! Here&apos;s an overview of your blog.
          </p>
        </div>
        <Link
          href="/admin/posts/new"
          className="inline-flex items-center gap-2 px-4 py-2.5 text-sm font-semibold text-white bg-blue-600 rounded-xl hover:bg-blue-700 transition-all self-start sm:self-auto shrink-0"
        >
          <PlusCircle className="w-4 h-4" />
          New Post
        </Link>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4 mb-8">
        {stats.map((stat) => (
          <div
            key={stat.label}
            className="bg-white rounded-xl border border-slate-200 p-5"
          >
            <div className="flex items-center justify-between mb-3">
              <span className="text-sm font-medium text-slate-500">{stat.label}</span>
              <div className={`w-9 h-9 rounded-lg flex items-center justify-center ${stat.color}`}>
                <stat.icon className="w-4.5 h-4.5" />
              </div>
            </div>
            <p className="text-2xl font-bold">{stat.value}</p>
          </div>
        ))}
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
        <div className="bg-green-50 rounded-xl p-5 border border-green-100">
          <div className="flex items-center gap-2 text-green-700 mb-1">
            <TrendingUp className="w-4 h-4" />
            <span className="text-sm font-medium">Published</span>
          </div>
          <p className="text-xl font-bold text-green-800">{data.publishedPosts}</p>
        </div>
        <div className="bg-yellow-50 rounded-xl p-5 border border-yellow-100">
          <div className="flex items-center gap-2 text-yellow-700 mb-1">
            <FileText className="w-4 h-4" />
            <span className="text-sm font-medium">Drafts</span>
          </div>
          <p className="text-xl font-bold text-yellow-800">{data.draftPosts}</p>
        </div>
        <div className="bg-blue-50 rounded-xl p-5 border border-blue-100">
          <div className="flex items-center gap-2 text-blue-700 mb-1">
            <Bot className="w-4 h-4" />
            <span className="text-sm font-medium">Auto Posts</span>
          </div>
          <p className="text-xl font-bold text-blue-800">{data.autoPosts}</p>
        </div>
      </div>

      {/* Recent Posts */}
      <div className="bg-white rounded-xl border border-slate-200">
        <div className="p-5 border-b border-slate-100 flex items-center justify-between">
          <h2 className="font-semibold">Recent Posts</h2>
          <Link
            href="/admin/posts"
            className="text-sm text-blue-600 hover:underline flex items-center gap-1"
          >
            View all <ArrowUpRight className="w-3.5 h-3.5" />
          </Link>
        </div>
        <div className="divide-y divide-slate-50">
          {data.recentPosts.map((post) => (
            <div key={post.id} className="p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-2 hover:bg-slate-50 transition-colors">
              <div className="flex-1 min-w-0">
                <Link
                  href={`/admin/posts/${post.id}`}
                  className="text-sm font-medium text-slate-800 hover:text-blue-600 truncate block"
                >
                  {post.title}
                </Link>
                <div className="flex items-center gap-3 mt-1">
                  <span className="text-xs text-slate-400">
                    {formatDate(post.createdAt)}
                  </span>
                  {post.autoGenerated && (
                    <span className="text-xs bg-amber-100 text-amber-700 px-2 py-0.5 rounded-full">
                      Auto
                    </span>
                  )}
                </div>
              </div>
              <div className="flex items-center gap-3 shrink-0">
                <span className="text-xs text-slate-400">{post.views} views</span>
                <span
                  className={`text-xs px-2.5 py-1 rounded-full font-medium ${
                    post.published
                      ? "bg-green-100 text-green-700"
                      : "bg-slate-100 text-slate-500"
                  }`}
                >
                  {post.published ? "Published" : "Draft"}
                </span>
              </div>
            </div>
          ))}
          {data.recentPosts.length === 0 && (
            <div className="p-8 text-center text-slate-400 text-sm">
              No posts yet. Create your first post!
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
